version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/aws-devops-zero-to-hero

hooks:
  ApplicationStop:
    - location: stop_container.sh
      timeout: 300
      runas: ubuntu

  ApplicationStart:
    - location: start_container.sh
      timeout: 300
      runas: ubuntu
